Repository pocketnetteam/pocketnet.gui, pull requests merged in 2022-08, with the labels that each got.

#629 Workflow actions to build platform apps
  .github/workflows/build.dev.yml
  .github/workflows/build.release.yml
Labels: ✨ enhancement

#581 Fix double tag in comment reply
  js/satolist.js
Labels: 🐛 bug

#580 Fix raw HTML entities in attached links
  js/functions.js
  js/satolist.js
Labels: 🐛 bug, deploy.dev

#618 docs: add logo to readme header
  README.md
Labels: deploy.dev, documentation

#633 refactoring: git workflow setup
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/build.macos.yml
  .github/workflows/deploy.pulls.dev.yml
  SECURITY.md
Labels: good first issue, in progress, refactoring, documentation

#589 Show where is video hosted
  components/share/index.css
  components/share/index.less
  components/share/templates/url.html
  css/common.css
  css/common.less
Labels: ✨ enhancement

#601 feat: localstorage synchronizer mechanism
  js/satolist.js
Labels: ✨ enhancement, deploy.dev

#565 Popup banner to invite users download apps
  js/_map.js
  js/app.js
  js/popups/index.js
  js/vendor/shadow-popup/css/popup.css
  js/vendor/shadow-popup/popup.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
Labels: ✨ enhancement

#632 New peertube servers deploy
  proxy16/proxy.js
Labels: peertube servers

#610 Localization fixes
  components/userslist/templates/users.html
  js/satolist.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
Labels: localizations

#638 refactor: apps building
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.pulls.dev.yml
Labels: refactoring, documentation

#622 Origin/feature/statistic
  components/post/index.js
  components/statistic/index.css
  components/statistic/index.js
  components/statistic/index.less
  components/statistic/templates/block.html
  components/statistic/templates/form.html
  components/statistic/templates/index.html
  components/userpage/index.css
  components/userpage/index.js
  components/userpage/index.less
  components/ustate/index.js
  components/ustate/templates/uscnt.html
  js/_map.js
  js/logger.js
  localization/en.js
  localization/ru.js
  proxy16/node/rpc.js
Labels: ✨ enhancement, deploy.dev

#636 fix: errors when submitting complaints
  components/complain/index.js
  js/kit.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
Labels: 🐛 bug, deploy.dev

#597 Translate pages
  components/test/index.js
  components/usersettings/index.js
  components/wallet/index.js
  js/satolist.js
Labels: 🐛 bug, deploy.dev

#593 Pkoin comment error
  components/pkoin/index.css
  components/pkoin/index.js
  components/pkoin/index.less
  components/pkoin/templates/fields.html
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: 🐛 bug, deploy.dev

#592 Video stalling errors logging
  components/lenta/index.js
  components/post/index.js
  js/logger.js
Labels: deploy.dev, logging

#644 fix: return by error removed verified users
  js/satolist.js
Labels: 🐛 bug

#646 patch: update limit's counter
  js/satolist.js
Labels: deploy.dev

#654 feat: night platform builds
  .github/workflows/deploy.pulls.dev.yml
  .github/workflows/night.bastyon.com.yml
  .github/workflows/pre.pocketnet.app.yml
  .github/workflows/test.pocketnet.app.yml
Labels: ✨ enhancement
