Repository pocketnetteam/pocketnet.gui, pull requests merged in 2022-05, with the labels that each got.

#439 Fix app dying when video deleted
  components/lenta/index.js
Labels: bug

#440 Change transport service (added queue)
  js/pwa-service-worker.js
  package-lock.json
  package.json
  proxy16/package-lock.json
  proxy16/package.json
  proxy16/transports.js
  tpls/main.js.tpl
Labels: enhancement

#451 Test accounts authorization route
  js/peertube.js
  js/satolist.js
Labels: deployed for tests

#450 Video posting before transcoding finishing
  components/lenta/index.js
  components/lenta/templates/share.html
  components/share/index.js
  js/kit.js
  js/peertube.js
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: deployed for tests

#438 Blur blocked user comment
  components/comments/index.css
  components/comments/index.js
  components/comments/templates/list.html
  components/comments/templates/metmenu.html
Labels: enhancement, in progress

#459 User complain feature and blocking rules
  components/complain/index.js
  components/lenta/templates/metmenu.html
  js/app.js
  js/kit.js
  js/satolist.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
  package-lock.json
Labels: moderation

#469 Boost button fix in article
  components/lenta/index.js
  components/post/index.js
Labels: bug

#470 User complain feature and blocking rules
  js/satolist.js
Labels: enhancement, new moderation

#476 User complain feature bug fix
  components/complain/index.css
  components/complain/index.js
  js/satolist.js
Labels: bug
