Repository pocketnetteam/pocketnet.gui, pull requests merged in 2022-07, with the labels that each got.

#540 Transports request was not awaited
  package-lock.json
  package.json
  proxy16/node/applications.js
Labels: 🐛 bug

#489 English localization issues
  localization/en.js
Labels: localizations

#503 Video player template fix
  components/share/templates/url.html
Labels: 🐛 bug, in progress

#567 Video Cabinet name editing fix + logging changes
  components/uploadpeertube/index.js
  components/videoCabinet/index.js
  js/logger.js
  localization/en.js
  localization/ru.js
Labels: ✨ enhancement

#570 Cordova configurations for iOS
  cordova/build.tpl.json
  cordova/package.json
  tpls/config.xml.tpl
Labels: ✨ enhancement

#509 Alternative ways to complain
  components/author/templates/metmenu.html
  components/comments/index.js
  components/comments/templates/metmenu.html
  components/complain/index.js
  components/complain/templates/index.html
  components/lenta/templates/metmenu.html
  js/kit.js
  js/logger.js
  js/satolist.js
  localization/en.js
  localization/es.js
  localization/ru.js
Labels: ✨ enhancement, deployed for tests

#462 Comment banner
  components/commentBanner/index.css
  components/commentBanner/index.js
  components/commentBanner/index.less
  components/commentBanner/templates/index.html
  components/comments/index.js
  components/comments/templates/index.html
  components/index.css
  components/lenta/index.js
  components/lenta/index.less
  components/lenta/templates/invitecomment.html
  components/lenta/templates/share.html
  components/lenta/templates/sharevideo.html
  css/main.css
  css/main.less
  images/comment.png
  js/_map.js
  js/satolist.js
  localization/en.js
  localization/es.js
  localization/ru.js
Labels: ✨ enhancement

#553 Recommendations banner and FAQ texts
  components/channel/index.js
  components/channel/templates/index.html
  components/recommendedusers/index.js
  components/registration/index.css
  components/registration/index.js
  components/registration/index.less
  components/registration/templates/bloggers.html
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: ✨ enhancement

#584 Fixed a memory leak when loading a snapshot database of a Node
  proxy16/node/applications.js
Labels: 🚫 invalid, in progress

#583 Hide boost for iOS application
  js/app.js
Labels: 🐛 bug

#595 New Videos servers formation
  proxy16/proxy.js
Labels: peertube servers
