Repository pocketnetteam/pocketnet.gui, pull requests merged in 2022-12, with the labels that each got.

#775 feat: add christmas design
  components/menu/index.css
  components/menu/index.less
  components/menu/templates/index.html
  img/christmas_bell.svg
  img/christmas_branch_left.svg
  img/christmas_branch_right.svg
  img/logotypes/bastyon_logo_black_christmas.svg
  img/logotypes/bastyon_logo_white_christmas.svg
  js/functions.js
  package.json
Labels: contribution type: ✨ feature, deploy.dev

#784 patch: packet 784
  components/leftpanel/templates/menu.html
  components/lenta/index.js
  components/menu/index.css
  components/menu/index.js
  components/menu/index.less
  components/post/index.js
  components/statistic/index.css
  components/statistic/index.less
  components/system16/index.css
  components/system16/index.js
  components/system16/index.less
  components/system16/templates/notificationcontent.html
  components/system16/templates/notificationcontenttable.html
  components/system16/templates/notificationuserstable.html
  js/lib/client/api.js
  js/satolist.js
  js/vendor/plyr.js
  peertube/294.chunk.js.map
  peertube/300.chunk.js.map
  peertube/543.chunk.js
  peertube/543.chunk.js.map
  peertube/555.chunk.js
  peertube/555.chunk.js.map
  peertube/639.chunk.js
  peertube/639.chunk.js.map
  peertube/647.chunk.js.map
  peertube/819.chunk.js.map
  peertube/875.chunk.js.map
  peertube/958.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
Labels: contribution type: 🧩 patch

#791 patch: disable popups for test environment
  js/app.js
Labels: contribution type: 🧩 patch

#786 fix: auth broken by notifications
  js/notifications.js
  js/satolist.js
Labels: contribution type: 🐛 fix

#792 fix: user-agent is not string in logs
  js/app.js
Labels: contribution type: 🐛 fix

#790 patch: six new video servers and some fixes
  components/videoCabinet/index.css
  components/videoCabinet/index.less
  js/peertube.js
  proxy16/peertube/index.js
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#797 fix: video description editing
  components/editVideoDescription/index.css
  components/editVideoDescription/index.js
  components/editVideoDescription/index.less
  components/editVideoDescription/templates/index.html
  components/videoCabinet/index.css
  components/videoCabinet/index.js
  components/videoCabinet/index.less
  js/_map.js
  tpls/index_el.html.tpl
Labels: contribution type: 🐛 fix

#808 patch: add new confirmed users
  js/satolist.js
Labels: contribution type: 🧩 patch

#805 feat: invitation to install pwa application on ios
  components/applications/index.css
  components/applications/index.less
  components/installios/index.css
  components/installios/index.js
  components/installios/index.less
  components/installios/templates/index.html
  img/applications_ios.jpg
  img/iosshareicon.svg
  js/_map.js
  js/app.js
  js/satolist.js
  localization/en.js
  localization/ru.js
  minimize.js
  package.json
Labels: contribution type: ✨ feature

#811 patch: remove pocketnet redirect banner
  js/app.js
  js/main.js
  js/satolist.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
  package.json
Labels: contribution type: 🧩 patch

#815 fix: meta configs introduced in PR 811
  minimize.js
  package.json
  tpls/manifest.json.tpl
Labels: contribution type: 🐛 fix

#820 fix: remove google-signin from firebasex
  cordova/cordova-plugin-firebasex/.editorconfig
  cordova/cordova-plugin-firebasex/.github/FUNDING.yml
  cordova/cordova-plugin-firebasex/.github/ISSUE_TEMPLATE/bug_report.md
  cordova/cordova-plugin-firebasex/.github/ISSUE_TEMPLATE/documentation-issue.md
  cordova/cordova-plugin-firebasex/.github/ISSUE_TEMPLATE/feature_request.md
  cordova/cordova-plugin-firebasex/.github/PULL_REQUEST_TEMPLATE.md
  cordova/cordova-plugin-firebasex/.github/stale.yml
  cordova/cordova-plugin-firebasex/.travis.yml
  cordova/cordova-plugin-firebasex/CHANGELOG.md
  cordova/cordova-plugin-firebasex/CODE_OF_CONDUCT.md
  cordova/cordova-plugin-firebasex/CONTRIBUTING.md
  cordova/cordova-plugin-firebasex/LICENSE
  cordova/cordova-plugin-firebasex/README.md
  cordova/cordova-plugin-firebasex/_config.yml
  cordova/cordova-plugin-firebasex/bump-version.js
  cordova/cordova-plugin-firebasex/package.json
  cordova/cordova-plugin-firebasex/plugin.xml
  cordova/cordova-plugin-firebasex/scripts/after_prepare.js
  cordova/cordova-plugin-firebasex/scripts/ios/after_plugin_install.js
  cordova/cordova-plugin-firebasex/scripts/ios/before_plugin_install.js
  cordova/cordova-plugin-firebasex/scripts/ios/before_plugin_uninstall.js
  cordova/cordova-plugin-firebasex/scripts/ios/helper.js
  cordova/cordova-plugin-firebasex/scripts/lib/android.js
  cordova/cordova-plugin-firebasex/scripts/lib/utilities.js
  cordova/cordova-plugin-firebasex/src/android/FirebasePlugin.java
  cordova/cordova-plugin-firebasex/src/android/FirebasePluginMessageReceiver.java
  cordova/cordova-plugin-firebasex/src/android/FirebasePluginMessageReceiverManager.java
  cordova/cordova-plugin-firebasex/src/android/FirebasePluginMessagingService.java
  cordova/cordova-plugin-firebasex/src/android/JavaScriptException.java
  cordova/cordova-plugin-firebasex/src/android/OnNotificationOpenReceiver.java
  cordova/cordova-plugin-firebasex/src/android/build.gradle
  cordova/cordova-plugin-firebasex/src/android/colors.xml
  cordova/cordova-plugin-firebasex/src/android/cordova-plugin-firebase-strings.xml
  cordova/cordova-plugin-firebasex/src/ios/AppDelegate+FirebasePlugin.h
  cordova/cordova-plugin-firebasex/src/ios/AppDelegate+FirebasePlugin.m
  cordova/cordova-plugin-firebasex/src/ios/FirebasePlugin.h
  cordova/cordova-plugin-firebasex/src/ios/FirebasePlugin.m
  cordova/cordova-plugin-firebasex/src/ios/FirebasePluginMessageReceiver.h
  cordova/cordova-plugin-firebasex/src/ios/FirebasePluginMessageReceiver.m
  cordova/cordova-plugin-firebasex/src/ios/FirebasePluginMessageReceiverManager.h
  cordova/cordova-plugin-firebasex/src/ios/FirebasePluginMessageReceiverManager.m
  cordova/cordova-plugin-firebasex/src/ios/GoogleService-Info.plist
  cordova/cordova-plugin-firebasex/types/index.d.ts
  cordova/cordova-plugin-firebasex/www/firebase.js
  cordova/package-lock.json
  cordova/package.json
Labels: deploy.dev

#819 patch: invitation to install pwa application on ios
  components/bastyon_iphone/index.css
  components/bastyon_iphone/index.js
  components/bastyon_iphone/index.less
  components/bastyon_iphone/templates/index.html
  js/_map.js
  js/satolist.js
  tpls/index.html.tpl
  tpls/index.php.tpl
  tpls/index_el.html.tpl
  tpls/indexcordova.html.tpl
Labels: deploy.dev, contribution type: 🧩 patch

#817 feat: add christmas design for chat
  components/menu/index.css
  components/menu/index.js
  components/menu/index.less
  components/menu/templates/index.html
  img/christmas_chat.svg
  img/christmas_search.svg
Labels: contribution type: ✨ feature, deploy.dev

#814 docs: missing conditions and terms in russian on mobile app
  components/terms/index.js
  components/terms/templates/en.html
  components/terms/templates/index.html
  components/terms/templates/ru.html
  localization/en.js
  localization/ru.js
Labels: deploy.dev, contribution type: 📖 documentation

#806 feat: share long post in mobile app
  .gitignore
  js/functions.js
  js/kit.js
Labels: contribution type: ✨ feature, deploy.dev

#821 fix: text editing window markup
  components/editVideoDescription/index.css
  components/editVideoDescription/index.less
  components/editVideoDescription/templates/index.html
Labels: contribution type: 🐛 fix, deploy.dev

#810 docs: fix whitepaper link in readme
  README.md
Labels: contribution type: 📖 documentation

#827 patch: invitation to install pwa application on ios styles
  components/bastyon_iphone/index.css
  components/bastyon_iphone/index.less
Labels: contribution type: 🧩 patch

#824 docs: faq page text edits
  components/faq/content.js
  components/faq/test.js
  js/satolist.js
  localization/en.js
  localization/it.js
  localization/ru.js
Labels: contribution type: 📖 documentation

#830 patch: localization and install ios pwa page
  components/bastyon_iphone/index.css
  components/bastyon_iphone/index.less
  components/bastyon_iphone/templates/index.html
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
  package.json
Labels: contribution type: 🧩 patch

#826 patch: recommended bloggers banner
  components/registration/index.css
  components/registration/index.js
  components/registration/index.less
  components/registration/templates/bloggers.html
Labels: contribution type: 🧩 patch

#837 repo: action better release title
  .github/workflows/build.release.yml
Labels: contribution type: 🚦 maintanance

#839 patсh: parse link and open chat
  components/welcome/index.js
  js/navn.js
  js/satolist.js
Labels: contribution type: 🧩 patch

#840 patch: optimization packet
  components/lenta/index.js
  components/main/index.js
  cordova/cordova-plugin-run-in-background/.gitignore
  cordova/cordova-plugin-run-in-background/.travis.yml
  cordova/cordova-plugin-run-in-background/package.json
  cordova/cordova-plugin-run-in-background/plugin.xml
  cordova/cordova-plugin-run-in-background/src/android/ForegroundService.java
  cordova/package-lock.json
  cordova/package.json
  js/videotransport.js
  package.json
  peertube/294.chunk.js.map
  peertube/300.chunk.js.map
  peertube/543.chunk.js
  peertube/543.chunk.js.map
  peertube/555.chunk.js.map
  peertube/639.chunk.js.map
  peertube/647.chunk.js
  peertube/647.chunk.js.LICENSE.txt
  peertube/647.chunk.js.map
  peertube/819.chunk.js.map
  peertube/875.chunk.js.map
  peertube/958.chunk.js
  peertube/958.chunk.js.LICENSE.txt
  peertube/958.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
  tpls/config.xml.tpl
Labels: contribution type: 🧩 patch

#834 patch: boost page interface
  components/boost/index.css
  components/boost/index.less
  components/boost/templates/index.html
  components/leftpanel/templates/footer.html
  img/Digifinex.png
  img/INDACOIN.22f2245a.svg
  img/ads-on-bastyon1-en.jpg
  img/ads-on-bastyon1.jpg
  img/ads-on-bastyon3-en.jpg
  img/ads-on-bastyon3.jpg
  img/bitforex-logo-Dark.fec7d7c3.svg
  img/bitforex.png
  img/boost/bitforex-logo-Dark.fec7d7c3.svg
  img/boost/p2p.png
  img/download.svg
  img/peer-to-peer-en.jpg
  img/peer-to-peer.jpg
  js/popups/index.js
  localization/en.js
  localization/ru.js
  package-lock.json
Labels: contribution type: 🧩 patch

#847 patch: android configs and video player
  .well-known/assetlinks.json
  components/camerapreview/index.js
  components/faq/index.js
  components/lenta/index.js
  components/post/index.js
  cordova/package-lock.json
  cordova/package.json
  js/_map.js
  js/app.js
  js/functions.js
  js/videotransport.js
  package-lock.json
  package.json
  peertube/284.chunk.js
  peertube/284.chunk.js.LICENSE.txt
  peertube/284.chunk.js.map
  peertube/294.chunk.js
  peertube/294.chunk.js.LICENSE.txt
  peertube/294.chunk.js.map
  peertube/300.chunk.js.map
  peertube/543.chunk.js
  peertube/543.chunk.js.map
  peertube/555.chunk.js
  peertube/555.chunk.js.map
  peertube/639.chunk.js
  peertube/639.chunk.js.map
  peertube/647.chunk.js
  peertube/647.chunk.js.LICENSE.txt
  peertube/647.chunk.js.map
  peertube/713.chunk.js
  peertube/713.chunk.js.map
  peertube/819.chunk.js
  peertube/819.chunk.js.LICENSE.txt
  peertube/819.chunk.js.map
  peertube/875.chunk.js.map
  peertube/958.chunk.js
  peertube/958.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.LICENSE.txt
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css
  peertube/video-embed.css.map
  tpls/config.xml.tpl
  tpls/index.html.tpl
  tpls/index.php.tpl
Labels: contribution type: 🧩 patch
