Repository pocketnetteam/pocketnet.gui, pull requests merged in 2022-11, with the labels that each got.

#726 fix: blocked comments and splash screen icon size
  components/authorization/index.js
  components/commentBanner/index.js
  components/comments/index.css
  components/comments/index.js
  components/comments/index.less
  components/comments/templates/list.html
  components/main/index.js
  components/menu/index.js
  components/navigation/index.js
  components/pkview/index.js
  components/registration/index.js
  components/registration/templates/moneyfail.html
  components/share/index.js
  components/socialshare2/index.js
  components/system16/templates/servercontent.html
  components/test/index.js
  components/uploadpeertube/index.js
  components/usersettings/templates/options.html
  components/videoCabinet/index.css
  components/videoCabinet/index.less
  css/main.css
  css/main.less
  js/app.js
  js/peertube.js
  js/satolist.js
  js/user.js
  localization/en.js
  localization/ru.js
  package.json
  peertube/141.chunk.js.map
  peertube/294.chunk.js.map
  peertube/300.chunk.js.map
  peertube/5.chunk.js.map
  peertube/526.chunk.js.map
  peertube/569.chunk.js.map
  peertube/647.chunk.js.map
  peertube/819.chunk.js.map
  peertube/875.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
  tpls/index.html.tpl
  tpls/index.php.tpl
  tpls/index_el.html.tpl
  tpls/indexcordova.html.tpl
Labels: contribution type: 🐛 fix

#727 hotfix: proxy connection on failed
  components/registration/templates/captcha.html
  js/lib/client/api.js
  js/satolist.js
Labels: contribution type: 🔥 hotfix

#729 patch: new video cabinet functionality
  components/uploadpeertube/index.js
  components/videoCabinet/index.css
  components/videoCabinet/index.js
  components/videoCabinet/index.less
  components/videoCabinet/templates/unpostedVideos.html
  components/videoCabinet/templates/videoList.html
  localization/en.js
  localization/ru.js
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#738 hotfix: set valid cordova version code
  package.json
Labels: contribution type: 🔥 hotfix

#739 patch: add new verified users
  js/satolist.js
  package.json
Labels: contribution type: 🧩 patch

#743 fix: top menu not showing up in old browsers
  components/menu/index.css
  components/menu/index.less
  css/main.css
  css/main.less
Labels: contribution type: 🐛 fix, deploy.dev

#742 docs: add browserstack text to readme
  README.md
Labels: contribution type: 📖 documentation

#740 fix: recommendations banner button width
  components/registration/index.css
  components/registration/index.less
Labels: contribution type: 🐛 fix

#746 patch: remove recommended bloggers from english branch
  components/registration/index.js
Labels: contribution type: 🧩 patch

#747 fix: recommendations load on post open
  components/post/index.js
Labels: contribution type: 🐛 fix

#748 fix: private key not showing
  js/user.js
  package.json
Labels: contribution type: 🐛 fix

#750 fix: recommendations load on post open try 2
  components/main/index.js
  js/satolist.js
Labels: contribution type: 🐛 fix

#751 patch: ios config localizations
  cordova/configs/de.lproj/InfoPlist.strings
  cordova/configs/es.lproj/InfoPlist.strings
  cordova/configs/fr.lproj/InfoPlist.strings
  cordova/configs/it.lproj/InfoPlist.strings
  cordova/configs/kr.lproj/InfoPlist.strings
  cordova/configs/ru.lproj/InfoPlist.strings
  cordova/configs/zh.lproj/InfoPlist.strings
  tpls/config.xml.tpl
Labels: contribution type: 🧩 patch

#736 feat: servers connection diagnostics page
  components/diagnosticsPage/index.css
  components/diagnosticsPage/index.js
  components/diagnosticsPage/index.less
  components/diagnosticsPage/templates/diagnoseProgress.html
  components/diagnosticsPage/templates/index.html
  components/diagnosticsPage/templates/mainBody.html
  components/diagnosticsPage/templates/mainError.html
  components/diagnosticsPage/templates/resultTable.html
  components/userpage/index.js
  components/usersettings/index.js
  components/usersettings/templates/diagnostics.html
  components/usersettings/templates/index.html
  js/_map.js
  js/logger.js
  js/peertube.js
  localization/en.js
  localization/ru.js
Labels: contribution type: ✨ feature, deploy.dev

#745 patch: top ranked videos instead of most commented
  components/main/index.js
Labels: contribution type: 🧩 patch

#728 feat: statistic for push notifications
  components/system16/index.css
  components/system16/index.js
  components/system16/index.less
  components/system16/templates/notificationcontent.html
  components/system16/templates/notificationcontenttable.html
  components/system16/templates/notificationuserstable.html
  components/system16/templates/proxycontent.html
  js/_map.js
  js/main.js
  js/satolist.js
  proxy16/kit.js
  proxy16/node/node.js
  proxy16/node/notifications.js
  proxy16/node/notificationsDictionary.js
  proxy16/node/wss.js
  proxy16/proxy.js
  proxy16/server/firebase.js
Labels: contribution type: ✨ feature

#694 patch: avatar gif image resize
  components/share/index.js
  components/test/index.js
  js/app.js
  js/functions.js
  js/vendor/gif-frames.min.js
  js/vendor/gif.js
  js/vendor/gif.worker.js
Labels: contribution type: 🧩 patch

#757 patch: add new proxy for push notifications
  proxy16/kit.js
Labels: contribution type: 🧩 patch

#760 patch: old browsers extended support
  components/menu/index.css
  components/menu/index.less
  components/usersettings/index.js
  components/videoCabinet/index.js
  js/app.js
  js/functions.js
  js/kit.js
  js/lib/pocketnet/htls.js
  js/main.js
  js/peertube.js
  js/polyfills.js
  js/pwa-service-worker.js
  js/satolist.js
  js/transports/proxified-fetch.js
  js/transports/proxified-fetch.ts
  js/vendor/joypixels.js
  js/videotransport.js
  localization/en.js
  localization/ru.js
  minimize.js
  peertube/141.chunk.js
  peertube/141.chunk.js.map
  peertube/294.chunk.js.map
  peertube/300.chunk.js
  peertube/300.chunk.js.map
  peertube/5.chunk.js
  peertube/5.chunk.js.map
  peertube/526.chunk.js
  peertube/526.chunk.js.map
  peertube/543.chunk.js
  peertube/543.chunk.js.map
  peertube/555.chunk.js
  peertube/555.chunk.js.map
  peertube/569.chunk.js
  peertube/569.chunk.js.map
  peertube/639.chunk.js
  peertube/639.chunk.js.map
  peertube/647.chunk.js
  peertube/647.chunk.js.map
  peertube/819.chunk.js
  peertube/819.chunk.js.map
  peertube/875.chunk.js.map
  peertube/958.chunk.js
  peertube/958.chunk.js.LICENSE.txt
  peertube/958.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
  proxy16/functions.js
  proxy16/node/notificationsDictionary.js
Labels: contribution type: 🧩 patch

#755 patch: remove apk updater for ios platform
  cordova/hooks/before-build.js
  cordova/package-lock.json
  cordova/package.json
  package.json
  tpls/config.xml.tpl
Labels: contribution type: 🧩 patch

#766 patch: servers connection diagnostics page
  components/diagnosticsPage/index.css
  components/diagnosticsPage/index.js
  components/diagnosticsPage/index.less
  components/diagnosticsPage/templates/index.html
  components/diagnosticsPage/templates/resultTable.html
  components/videoCabinet/index.css
  components/videoCabinet/index.js
  components/videoCabinet/index.less
  js/_map.js
  js/vendor/ua-parser.min.js
  localization/en.js
  localization/ru.js
  tpls/index_el.html.tpl
Labels: contribution type: 🧩 patch

#763 patch: statistics outside of reputation page
  components/statistic/index.css
  components/statistic/index.js
  components/statistic/index.less
  components/statistic/templates/block.html
  components/statistic/templates/bonusProgram.html
  components/statistic/templates/form.html
  components/statistic/templates/index.html
  components/userpage/index.css
  components/userpage/index.js
  components/userpage/index.less
  components/ustate/index.js
  js/_map.js
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: contribution type: 🧩 patch

#768 patch: use android gallery for image upload
  components/camerapreview/index.css
  components/camerapreview/index.js
  components/camerapreview/index.less
  components/camerapreview/templates/index.html
  js/app.js
  js/functions.js
  js/satolist.js
  package.json
Labels: contribution type: 🧩 patch

#772 fix: apps download popup not showing
  js/_map.js
Labels: contribution type: 🐛 fix

#773 fix: old browsers peertube player support
  components/usersettings/templates/index.html
  js/navn.js
  peertube/294.chunk.js.map
  peertube/300.chunk.js.map
  peertube/543.chunk.js.map
  peertube/555.chunk.js.map
  peertube/639.chunk.js
  peertube/639.chunk.js.map
  peertube/647.chunk.js.map
  peertube/819.chunk.js.map
  peertube/875.chunk.js.map
  peertube/958.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
Labels: contribution type: 🐛 fix

#779 patch: packet 779
  js/satolist.js
  package.json
Labels: contribution type: 🧩 patch

#691 patch: node selection locales
  components/system16/index.js
  localization/en.js
  localization/ru.js
Labels: contribution type: 🧩 patch

#752 patch: article text part in preview
  components/lenta/index.css
  components/lenta/index.less
  components/lenta/templates/sharearticle.html
  css/common.css
  css/common.less
Labels: contribution type: 🧩 patch

#781 fix: app prevents macos shutdown
  tpls/main.js.tpl
Labels: contribution type: 🐛 fix

#703 feat: save post functionality for all platforms
  components/downloadMedia/index.css
  components/downloadMedia/index.js
  components/downloadMedia/index.less
  components/downloadMedia/templates/index.html
  components/leftpanel/templates/menu.html
  components/lenta/templates/metmenu.html
  components/main/index.js
  components/toppanel/index.js
  cordova/cordova-plugin-file-transfer/src/android/FileTransfer.java
  js/_map.js
  js/app.js
  js/electron/video-download.js
  js/satolist.js
  js/vendor/plyr.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
  php/og.php
  tpls/main.js.tpl
Labels: contribution type: ✨ feature, deploy.dev

#762 patch: logger functionality
  js/app.js
  js/logger.js
  js/vendor/vue/vue.js
Labels: contribution type: 🧩 patch
