Repository pocketnetteam/pocketnet.gui, pull requests merged in 2022-10, with the labels that each got.

#698 feat: boost page
  components/boost/index.css
  components/boost/index.js
  components/boost/index.less
  components/boost/templates/index.html
  img/boost/03.png
  img/boost/04.png
  img/boost/05.png
  img/boost/06.png
  img/boost/07.png
  img/boost/08.png
  img/boost/logo-78.png
  img/boost/logo-79.png
  localization/en.js
  localization/ru.js
Labels: contribution type: ✨ feature, deploy.dev

#696 fix: width limits for node address row
  components/system16/index.css
  components/system16/index.less
Labels: contribution type: 🐛 fix

#697 patch: packet 697
  components/post/index.js
  js/functions.js
  tpls/index.html.tpl
  tpls/index.php.tpl
  tpls/index_el.html.tpl
  tpls/indexcordova.html.tpl
  tpls/openapi.html.tpl
Labels: contribution type: 🧩 patch

#699 patch: set version to 0.8.17
  package-lock.json
  package.json
Labels: contribution type: 🧩 patch

#707 patch: two new video servers
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#709 workflow: set java 11 for android build and update the packages
  .github/workflows/build.dev.yml
  .github/workflows/deploy.pulls.dev.yml
  .github/workflows/night.bastyon.com.yml
  .github/workflows/night.test.bastyon.com.yml
  cordova/cordova-plugin-badge/CHANGELOG.md
  cordova/cordova-plugin-badge/LICENSE
  cordova/cordova-plugin-badge/README.md
  cordova/cordova-plugin-badge/images/android.png
  cordova/cordova-plugin-badge/images/ios-permission.png
  cordova/cordova-plugin-badge/images/ios.png
  cordova/cordova-plugin-badge/images/osx-badge.png
  cordova/cordova-plugin-badge/images/osx-circular.png
  cordova/cordova-plugin-badge/images/osx-download.png
  cordova/cordova-plugin-badge/images/windows.png
  cordova/cordova-plugin-badge/package.json
  cordova/cordova-plugin-badge/plugin.xml
  cordova/cordova-plugin-badge/src/android/Badge.java
  cordova/cordova-plugin-badge/src/android/BadgeImpl.java
  cordova/cordova-plugin-badge/src/android/badge.gradle
  cordova/cordova-plugin-badge/src/browser/BadgeProxy.js
  cordova/cordova-plugin-badge/src/browser/favico.min.js
  cordova/cordova-plugin-badge/src/ios/APPBadge.h
  cordova/cordova-plugin-badge/src/ios/APPBadge.m
  cordova/cordova-plugin-badge/src/osx/APPBadge.h
  cordova/cordova-plugin-badge/src/osx/APPBadge.m
  cordova/cordova-plugin-badge/src/osx/DockCircularProgressBar.h
  cordova/cordova-plugin-badge/src/osx/DockCircularProgressBar.mm
  cordova/cordova-plugin-badge/src/osx/DockDownloadProgressBar.h
  cordova/cordova-plugin-badge/src/osx/DockDownloadProgressBar.mm
  cordova/cordova-plugin-badge/src/windows/BadgeProxy.js
  cordova/cordova-plugin-badge/tests/plugin.xml
  cordova/cordova-plugin-badge/tests/tests.js
  cordova/cordova-plugin-badge/www/badge.js
  cordova/package-lock.json
  cordova/package.json
  tpls/config.xml.tpl
Labels: contribution type: 🧩 patch

#621 feat: update push notifications functionality
  components/share/index.js
  components/system16/templates/nodescontenttable.html
  firebase-messaging-sw.js
  js/_map.js
  js/main.js
  js/pwa-service-worker.js
  js/satolist.js
  js/vendor/firebase-app.js
  js/vendor/firebase-messaging.js
  proxy16/kit.js
  proxy16/node/control.js
  proxy16/node/manager.js
  proxy16/node/node.js
  proxy16/node/notifications.js
  proxy16/node/notificationsDictionary.js
  proxy16/node/rpc.js
  proxy16/node/testnode.js
  proxy16/node/wss.js
  proxy16/pocketnet.js
  proxy16/proxy.js
  proxy16/server/firebase.js
  tpls/service-worker.js.tpl
Labels: contribution type: ✨ feature, deploy.dev

#716 hotfix: invalid named variable used
  js/main.js
  package.json
Labels: contribution type: 🔥 hotfix

#720 patch: push notifications node server change
  components/comments/index.js
  components/usersettings/templates/index.html
  js/app.js
  js/satolist.js
  proxy16/kit.js
  proxy16/node/notifications.js
  proxy16/node/notificationsDictionary.js
  proxy16/node/wss.js
  tpls/index.html.tpl
Labels: contribution type: 🧩 patch

#719 patch: informative error for no video data
  js/satolist.js
Labels: contribution type: 🧩 patch

#686 patch: video cabinet localizations
  localization/en.js
  localization/ru.js
Labels: contribution type: 🧩 patch

#717 fix: macos errors on electron app quit
  js/transports/proxified-fetch.js
  js/transports/proxified-fetch.ts
  js/transports/tsconfig.json
Labels: contribution type: 🐛 fix, platform: macos

#721 patch: disable new push notifications functionality
  components/post/index.css
  components/post/index.less
  js/main.js
  js/peertube.js
  js/satolist.js
  js/video-uploader.js
  package.json
  proxy16/cli.js
  proxy16/logger.js
  proxy16/node/notifications.js
  proxy16/proxy.js
  proxy16/server/firebase.js
Labels: contribution type: 🧩 patch

#722 refactor: video download continuity
  components/lenta/index.css
  components/lenta/index.js
  components/lenta/index.less
  components/lenta/templates/share.html
  components/lenta/templates/sharevideo.html
  components/post/index.css
  components/post/index.js
  components/post/index.less
  css/common.css
  css/common.less
  js/electron/video-download.js
  js/functions.js
  js/satolist.js
  tpls/main.js.tpl
Labels: deploy.dev, contribution type: 💎 refactoring

#710 feat: new comment banner functionality
  components/commentBanner/index.css
  components/commentBanner/index.js
  components/commentBanner/index.less
  components/commentBanner/templates/index.html
  components/comments/index.js
  components/lenta/index.js
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: contribution type: ✨ feature, deploy.pause
