Repository pocketnetteam/pocketnet.gui, pull requests merged in 2022-09, with the labels that each got.

#664 fix: easynode install new version
  proxy16/node/control.js
Labels: deploy.dev

#672 fix: add rendered class to videos
  components/lenta/templates/groupshares.html
  components/lenta/templates/shares.html
Labels: 🐛 bug

#674 fix: clear inactive test nodes
  proxy16/kit.js
Labels: contribution type: 🐛 fix

#677 docs: add badge icons in readme
  README.md
Labels: state: 🆗 ready for review

#678 feat: extra logging
  components/lenta/index.js
  components/recommendations/index.js
  components/registration/index.js
  js/app.js
  js/logger.js
  js/satolist.js
Labels: contribution type: ✨ feature, deploy.dev

#662 patch: Editing reserved accounts
  components/test/index.js
  js/kit.js
Labels: deploy.dev, contribution type: 🧩 patch, state: 🆗 ready for review

#658 feat: separate bloggers for English and Russian sections
  components/registration/index.js
  js/satolist.js
Labels: contribution type: ✨ feature, deploy.dev

#673 fix: easynode source link
  proxy16/node/control.js
Labels: contribution type: 🐛 fix, deploy.dev

#681 fix: minor changes: scroll focus, link from chat
  components/comments/index.js
  components/post/index.js
  components/userpage/index.js
  js/kit.js
  js/satolist.js
  package.json
  peertube/141.chunk.js.map
  peertube/294.chunk.js.map
  peertube/300.chunk.js.map
  peertube/5.chunk.js.map
  peertube/526.chunk.js.map
  peertube/569.chunk.js.map
  peertube/647.chunk.js.map
  peertube/819.chunk.js.map
  peertube/875.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
Labels: contribution type: 🐛 fix

#676 fix: Comments in statistic
  components/statistic/index.css
  components/statistic/index.js
  components/statistic/index.less
  components/statistic/templates/block.html
  components/statistic/templates/form.html
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: contribution type: 🐛 fix, deploy.dev

#623 feat: top posts to most commented
  components/leftpanel/index.css
  components/leftpanel/index.js
  components/leftpanel/index.less
  components/leftpanel/templates/menu.html
  components/leftpanel/templates/top.html
  components/lenta/index.js
  components/main/index.js
  components/main/templates/menu.html
  components/toppanel/index.js
  components/videoCabinet/index.js
  components/videoCabinet/templates/index.html
  js/satolist.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
  proxy16/node/manager.js
  proxy16/node/rpc.js
  proxy16/server/cache.js
Labels: contribution type: ✨ feature, deploy.dev

#684 patch: rcp calls logging
  js/lib/client/api.js
Labels: deploy.dev, contribution type: 🧩 patch

#689 hotfix: cordova run app in background plugin
  cordova/package.json
Labels: contribution type: 🔥 hotfix

#693 fix: virtual keyboard api, camerapreview optimizations, gifs
  components/camerapreview/index.js
  css/main.css
  css/main.less
  js/app.js
  js/functions.js
  js/satolist.js
  package.json
Labels: contribution type: 🐛 fix
