Repository pocketnetteam/pocketnet.gui, pull requests merged in 2023-08, with the labels that each got.

#1082 hotfix: issues after transactions refactoring
  chat/matrix-element.11.js
  chat/matrix-element.11.js.map
  chat/matrix-element.11.min.js
  chat/matrix-element.11.min.js.map
  components/pkview/index.css
  components/pkview/index.less
  components/registration/index.js
  components/registration/templates/bloggers.html
  js/electron/video-download.js
  js/lib/client/actions.js
  js/satolist.js
  package-lock.json
  package.json
Labels: contribution type: 🔥 hotfix

#1083 fix: tor broadcaster not being started
  js/_map.js
  js/broadcaster.js
  js/satolist.js
Labels: contribution type: 🐛 fix

#1084 fix: all tor events being dismounted and likes functionality
  components/post/index.js
  js/broadcaster.js
  js/satolist.js
Labels: contribution type: 🐛 fix

#1085 patch: peertube servers list
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#1086 fix: push notifications, feat: add translate api
  components/comments/index.css
  components/comments/index.less
  components/lenta/index.js
  components/lenta/templates/share.html
  components/post/index.js
  components/system16/index.css
  components/system16/index.js
  components/system16/index.less
  components/system16/templates/proxycontent.html
  components/system16/templates/translateapi.html
  css/common.css
  css/common.less
  js/app.js
  js/functions.js
  js/kit.js
  js/lib/client/api.js
  js/lib/client/sdk.js
  js/main.js
  js/navn.js
  js/satolist.js
  package.json
  peertube/284.chunk.js.map
  peertube/300.chunk.js.map
  peertube/524.chunk.js.map
  peertube/875.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css
  peertube/video-embed.css.map
  proxy16/functions.js
  proxy16/kit.js
  proxy16/node/node.js
  proxy16/proxy.js
  proxy16/server/translateapi.js
  proxy16/wallet/wallet.js
Labels: contribution type: 🐛 fix, contribution type: ✨ feature

#1090 fix: window spinner
  js/functions.js
  js/module.js
  js/satolist.js
Labels: contribution type: 🐛 fix

#1089 fix: show version on mobile when update available
  components/userpage/index.css
  components/userpage/index.less
  components/userpage/templates/contents.html
Labels: contribution type: 🐛 fix

#1091 fix: missing comment banner
  components/commentBanner/index.js
  components/lenta/index.js
  components/post/index.js
Labels: contribution type: 🐛 fix

#1095 repo: workflows update
  .github/workflows/analyze-conflicts.yml
  .github/workflows/deploy.proxy.yml
  .github/workflows/deploy.pulls.dev.yml
Labels: contribution type: 🚦 maintanance

#1098 fix: navigation bar color and images
  components/about/index.js
  components/comments/index.css
  components/comments/index.js
  components/comments/index.less
  components/main/index.js
  components/welcome/index.js
  js/app.js
  js/functions.js
  js/functionsfirst.js
  js/lib/client/sdk.js
  js/satolist.js
  package.json
  tpls/config.xml.tpl
Labels: contribution type: 🐛 fix
