Repository pocketnetteam/pocketnet.gui, pull requests merged in 2023-04, with the labels that each got.

#981 patch: ipfs video links support and embed media player fixes
  components/bestposts/index.js
  components/lenta/index.js
  components/post/index.js
  components/share/index.js
  components/share/templates/url.html
  components/socialshare2/index.js
  js/functions.js
  js/kit.js
  js/satolist.js
  js/vendor/plyr.js
  package-lock.json
  package.json
Labels: contribution type: 🐛 fix, deploy.dev

#1005 hotfix: enable mirror servers
  proxy16/proxy.js
Labels: contribution type: 🔥 hotfix

#995 feat: ability to donate project with pkoin
  components/donations/index.js
Labels: contribution type: ✨ feature

#992 patch: packet 992
  components/authorization/index.js
  components/registration/index.js
  components/share/index.js
  components/share/templates/postline.html
  js/functions.js
  js/main.js
  js/satolist.js
  js/user.js
Labels: contribution type: 🧩 patch

#1007 fix: android keyboard and peertube player
  cordova/cordova-plugin-ionic-keyboard/src/android/CDVIonicKeyboard.java
  cordova/cordova-plugin-ionic-keyboard/www/android/keyboard.js
  cordova/package-lock.json
  peertube/284.chunk.js
  peertube/284.chunk.js.map
  peertube/300.chunk.js.map
  peertube/524.chunk.js
  peertube/524.chunk.js.map
  peertube/875.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
Labels: contribution type: 🐛 fix

#1011 patch: add new peertube servers and mark some old
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#1014 patch: add gf apk
  .github/workflows/deploy.pulls.dev.yml
  .github/workflows/night.bastyon.com.yml
  cordova/build.tpl.json
  js/app.js
  js/satolist.js
  minimize.js
Labels: deploy.dev

#1015 fix: night deploy workflow
  .github/workflows/night.bastyon.com.yml
Labels: contribution type: 🐛 fix

#1017 patch: pinfo classes
  js/functions.js
  js/kit.js
Labels: contribution type: 🧩 patch

#1006 feat: add earnings page in place of statistics
  components/earnings/index.css
  components/earnings/index.js
  components/earnings/index.less
  components/earnings/templates/index.html
  components/earnings/templates/total.html
  components/statistic/index.css
  components/statistic/index.js
  components/statistic/index.less
  components/statistic/templates/block.html
  components/statistic/templates/bonusProgram.html
  components/statistic/templates/form.html
  components/statistic/templates/index.html
  components/userpage/index.js
  js/_map.js
  localization/en.js
  localization/ru.js
  proxy16/node/rpc.js
  proxy16/package-lock.json
Labels: contribution type: ✨ feature

#1024 fix: base64 in images and css rules share
  components/share/index.css
  components/share/index.js
  components/share/index.less
  components/share/templates/postline.html
  js/functions.js
  localization/ru.js
Labels: contribution type: 🐛 fix
