Repository pocketnetteam/pocketnet.gui, pull requests merged in 2023-05, with the labels that each got.

#1031 fix: left footer, left panel styles, how to buy page
  components/categories/index.css
  components/categories/index.less
  components/howtobuy/index.css
  components/howtobuy/index.less
  components/leftpanel/templates/footer.html
  localization/en.js
  localization/ru.js
Labels: contribution type: 🐛 fix, deploy.dev

#1029 fix: video back button area
  css/main.css
  css/main.less
  js/satolist.js
Labels: contribution type: 🐛 fix, deploy.dev

#1028 feat: clear local storage
  components/usersettings/index.css
  components/usersettings/index.js
  components/usersettings/index.less
  components/usersettings/templates/cache.html
  localization/en.js
  localization/ru.js
Labels: contribution type: ✨ feature, deploy.dev

#1036 patch: faster ipfs gateway
  components/share/index.js
  js/vendor/plyr.js
Labels: contribution type: 🧩 patch

#1040 feat: ipfs video thumbnail support
  components/lenta/templates/share.html
  components/share/templates/url.html
  js/vendor/plyr.js
  package-lock.json
Labels: contribution type: ✨ feature

#1043 fix: image upload show conditions
  components/share/templates/postline.html
  js/kit.js
Labels: contribution type: 🐛 fix

#1046 patch: peertube servers list
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#1045 patch: transactions logs add more details
  proxy16/proxy.js
Labels: deploy.dev, contribution type: 🧩 patch

#1047 patch: proxies list update
  .github/workflows/deploy.proxy.yml
  js/main.js
  js/openapi.js
Labels: contribution type: 🧩 patch, contribution type: 🚦 maintanance

#1048 hotfix: transaction logs shadowed node object
  proxy16/proxy.js
Labels: contribution type: 🔥 hotfix
