Repository pocketnetteam/pocketnet.gui, pull requests merged in 2023-02, with the labels that each got.

#845 patch: blogger list
  js/satolist.js
Labels: contribution type: 🧩 patch

#917 fix: empty donation addresses
  js/kit.js
Labels: contribution type: 🐛 fix, deploy.dev

#914 patch: audience reach statistics on post boost
  components/pkoin/index.css
  components/pkoin/index.js
  components/pkoin/index.less
  components/pkoin/templates/boostinfo.html
  components/pkview/index.css
  components/pkview/index.less
  localization/en.js
  localization/ru.js
Labels: deploy.dev, contribution type: 🧩 patch

#912 patch: enable audio files upload
  components/leftpanel/templates/menu.html
  components/lenta/index.js
  components/share/index.css
  components/share/index.js
  components/share/index.less
  components/share/templates/postline.html
  components/share/templates/url.html
  components/uploadpeertube/templates/index.html
  css/main.css
  css/main.less
  js/kit.js
  localization/en.js
  localization/ru.js
  peertube/284.chunk.js.map
  peertube/300.chunk.js.map
  peertube/524.chunk.js
  peertube/524.chunk.js.map
  peertube/875.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css
  peertube/video-embed.css.map
Labels: deploy.dev, contribution type: 🧩 patch

#924 patch: calls ui update
  js/bastyonCalls/bastyonCalls.min.js
Labels: deploy.dev

#921 patch: server selection for image upload
  js/image-uploader.js
Labels: deploy.dev, contribution type: 🧩 patch

#920 feat: ability to delete all post comments by author
  components/comments/index.js
  components/comments/templates/metmenu.html
Labels: contribution type: ✨ feature, deploy.dev

#908 patch: registration to mark that email is not mandatory
  components/test/index.css
  components/test/index.js
  components/test/index.less
  components/test/templates/options.html
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
Labels: deploy.dev, contribution type: 🧩 patch

#903 unableToAuthorizeBody new text
  localization/en.js
  localization/ru.js
Labels: deploy.dev

#929 patch: staking profit formula update
  components/easynode/index.js
Labels: contribution type: 🧩 patch

#931 patch: enable calls functionality
  js/satolist.js
Labels: contribution type: 🧩 patch

#932 repo: fix deploy workflow for linux binaries
  .github/workflows/night.bastyon.com.yml
Labels: contribution type: 🚦 maintanance

#933 refactor: donations functionality
  components/donations/index.css
  components/donations/index.js
  components/donations/index.less
  components/donations/templates/address.html
  components/donations/templates/index.html
  components/donations/templates/status.html
  components/donations/templates/support.html
  components/donations/templates/ways.html
  components/leftpanel/index.css
  components/leftpanel/index.less
  components/userpage/templates/contents.html
  js/_map.js
  js/satolist.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/ru.js
Labels: contribution type: 💎 refactoring

#936 patch: boost page always show audience reach
  components/pkoin/index.css
  components/pkoin/index.js
  components/pkoin/index.less
  components/pkoin/templates/boostinfo.html
Labels: deploy.dev, contribution type: 🧩 patch

#940 fix: some small errors
  js/satolist.js
  package.json
  proxy16/node/notifications.js
  proxy16/node/rpc.js
Labels: contribution type: 🐛 fix

#941 fix: donations functionality
  components/donations/index.js
  components/leftpanel/index.css
  components/leftpanel/index.js
  components/leftpanel/index.less
  components/leftpanel/templates/footer.html
  components/userpage/templates/contents.html
  localization/en.js
  localization/ru.js
Labels: contribution type: 🐛 fix

#942 fix: remove donation for mobile app
  components/userpage/templates/contents.html
Labels: contribution type: 🐛 fix

#945 fix: cordova android icons
  cordova/resources/android/icon/drawable-hdpi-icon.png
  cordova/resources/android/icon/drawable-ldpi-icon.png
  cordova/resources/android/icon/drawable-mdpi-icon.png
  cordova/resources/android/icon/drawable-xhdpi-icon.png
  cordova/resources/android/icon/drawable-xxhdpi-icon.png
  cordova/resources/android/icon/drawable-xxxhdpi-icon.png
  cordova/resources/icon.png
  cordova/resources/ios/icon/icon-1024.png
  cordova/resources/ios/icon/icon-108@2x.png
  cordova/resources/ios/icon/icon-20.png
  cordova/resources/ios/icon/icon-20@2x.png
  cordova/resources/ios/icon/icon-20@3x.png
  cordova/resources/ios/icon/icon-24@2x.png
  cordova/resources/ios/icon/icon-27.5@2x.png
  cordova/resources/ios/icon/icon-29.png
  cordova/resources/ios/icon/icon-29@2x.png
  cordova/resources/ios/icon/icon-29@3x.png
  cordova/resources/ios/icon/icon-40.png
  cordova/resources/ios/icon/icon-40@2x.png
  cordova/resources/ios/icon/icon-40@3x.png
  cordova/resources/ios/icon/icon-44@2x.png
  cordova/resources/ios/icon/icon-50.png
  cordova/resources/ios/icon/icon-50@2x.png
  cordova/resources/ios/icon/icon-60.png
  cordova/resources/ios/icon/icon-60@2x.png
  cordova/resources/ios/icon/icon-60@3x.png
  cordova/resources/ios/icon/icon-72.png
  cordova/resources/ios/icon/icon-72@2x.png
  cordova/resources/ios/icon/icon-76.png
  cordova/resources/ios/icon/icon-76@2x.png
  cordova/resources/ios/icon/icon-83.5@2x.png
  cordova/resources/ios/icon/icon-86@2x.png
  cordova/resources/ios/icon/icon-98@2x.png
  cordova/resources/ios/icon/icon.png
  cordova/resources/ios/icon/icon@2x.png
Labels: contribution type: 🐛 fix

#946 fix: cordova icons, android
  cordova/resources/android/icon/drawable-hdpi-icon.png
  cordova/resources/android/icon/drawable-ldpi-icon.png
  cordova/resources/android/icon/drawable-mdpi-icon.png
  cordova/resources/android/icon/drawable-xhdpi-icon.png
  cordova/resources/android/icon/drawable-xxhdpi-icon.png
  cordova/resources/android/icon/drawable-xxxhdpi-icon.png
  cordova/resources/icon.png
  cordova/resources/ios/icon/icon-1024.png
  cordova/resources/ios/icon/icon-108@2x.png
  cordova/resources/ios/icon/icon-20.png
  cordova/resources/ios/icon/icon-20@2x.png
  cordova/resources/ios/icon/icon-20@3x.png
  cordova/resources/ios/icon/icon-24@2x.png
  cordova/resources/ios/icon/icon-27.5@2x.png
  cordova/resources/ios/icon/icon-29.png
  cordova/resources/ios/icon/icon-29@2x.png
  cordova/resources/ios/icon/icon-29@3x.png
  cordova/resources/ios/icon/icon-40.png
  cordova/resources/ios/icon/icon-40@2x.png
  cordova/resources/ios/icon/icon-40@3x.png
  cordova/resources/ios/icon/icon-44@2x.png
  cordova/resources/ios/icon/icon-50.png
  cordova/resources/ios/icon/icon-50@2x.png
  cordova/resources/ios/icon/icon-60.png
  cordova/resources/ios/icon/icon-60@2x.png
  cordova/resources/ios/icon/icon-60@3x.png
  cordova/resources/ios/icon/icon-72.png
  cordova/resources/ios/icon/icon-72@2x.png
  cordova/resources/ios/icon/icon-76.png
  cordova/resources/ios/icon/icon-76@2x.png
  cordova/resources/ios/icon/icon-83.5@2x.png
  cordova/resources/ios/icon/icon-86@2x.png
  cordova/resources/ios/icon/icon-98@2x.png
  cordova/resources/ios/icon/icon.png
  cordova/resources/ios/icon/icon@2x.png
  package.json
  tpls/config.xml.tpl
Labels: contribution type: 🐛 fix
