Repository pocketnetteam/pocketnet.gui, pull requests merged in 2023-07, with the labels that each got.

#1059 patch: peertube servers list and dedicated conditions update
  js/peertube.js
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#1058 fix: not posted videos not disappearing in video cabinet
  components/videoCabinet/index.js
  js/satolist.js
Labels: contribution type: 🐛 fix

#1060 fix: video playing issues
  package.json
  peertube/284.chunk.js
  peertube/284.chunk.js.map
  peertube/300.chunk.js.map
  peertube/524.chunk.js.map
  peertube/875.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
Labels: contribution type: 🐛 fix

#1030 feat: mobile app update ui
  components/updatenotifier/index.css
  components/updatenotifier/index.js
  components/updatenotifier/index.less
  components/updatenotifier/templates/index.html
  img/clouds.svg
  img/waves.svg
  img/white_logo.svg
  js/_map.js
  js/app.js
  js/satolist.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
Labels: contribution type: ✨ feature

#1065 patch: peertube servers list
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#1069 fix: some issues in cabinet
  components/uploadpeertube/index.js
  components/videoCabinet/index.js
  js/peertube.js
Labels: contribution type: 🐛 fix

#1070 fix: matroska video upload
  components/uploadpeertube/index.js
  js/functions.js
  js/polyfills.js
Labels: contribution type: 🐛 fix

#1072 fix: comment answer name
  components/comments/index.js
  package.json
Labels: contribution type: 🐛 fix

#1077 hotfix: linkify library in electron
  tpls/index_el.html.tpl
Labels: contribution type: 🔥 hotfix

#1078 hotfix: issues after transactions refactoring
  components/articlesv/index.less
  components/comments/index.js
  components/lenta/index.js
  components/main/index.js
  components/mobilesearch/index.js
  components/post/index.js
  components/registration/templates/bloggers.html
  components/share/index.js
  components/userpage/index.js
  css/main.css
  css/main.less
  js/app.js
  js/functionsfirst.js
  js/kit.js
  js/lib/client/actions.js
  js/lib/client/api.js
  js/lib/client/sdk.js
  js/satolist.js
  js/user.js
  localization/en.js
  localization/ru.js
  package-lock.json
  package.json
  proxy16/kit.js
  proxy16/node/manager.js
  proxy16/node/rpc.js
Labels: contribution type: 🔥 hotfix

#1080 repo: update broken latest links in readme
  README.md
Labels: contribution type: 🚦 maintanance
