Repository pocketnetteam/pocketnet.gui, pull requests merged in 2023-03, with the labels that each got.

#953 fix: donations support ticket request query
  components/donations/index.js
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: contribution type: 🐛 fix

#957 fix: Leftpanel minor fixes
  components/leftpanel/templates/footer.html
Labels: deploy.dev

#959 Patch: How to buy
  components/boost/index.css
  components/boost/templates/index.html
  components/howtobuy/index.css
  components/howtobuy/index.js
  components/howtobuy/index.less
  components/howtobuy/templates/index.html
  components/leftpanel/templates/footer.html
  img/chat_en.png
  img/chat_ru.jpg
  img/seller_en.jpg
  img/seller_ru.jpg
  js/_map.js
  localization/en.js
  localization/ru.js
Labels: deploy.dev

#960 Patch: Boost page
  components/boost/index.css
  localization/en.js
  localization/ru.js
Labels: deploy.dev

#962 fix: destroy processes on Proxy
  proxy16/kit.js
  proxy16/node/manager.js
  proxy16/proxy.js
Labels: contribution type: 🐛 fix

#947 feat: show built version badge sha
  .github/actions/build.macos.yml
  .github/workflows/build.dev.yml
  .github/workflows/deploy.pulls.dev.yml
  .github/workflows/deploy.web.yml
  .github/workflows/night.bastyon.com.yml
  .github/workflows/night.test.bastyon.com.yml
  .github/workflows/pre.pocketnet.app.yml
  .github/workflows/test.pocketnet.app.yml
  components/leftpanel/index.css
  components/leftpanel/index.js
  components/leftpanel/index.less
  components/leftpanel/templates/footer.html
  components/userpage/index.css
  components/userpage/index.js
  components/userpage/index.less
  components/userpage/templates/contents.html
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
  minimize.js
Labels: contribution type: ✨ feature

#966 patch: pass fa icons into chat
  js/satolist.js
Labels: contribution type: 🧩 patch

#964 fix: boost page styles
  components/pkoin/index.css
  components/pkoin/index.less
Labels: contribution type: 🐛 fix

#968 fix: localization issues
  localization/ru.js
Labels: contribution type: 🐛 fix

#970 patch: application network transport system
  components/system16/index.js
  components/system16/templates/webserveradmin.html
  components/transportsmanagement/templates/settings.html
  css/common.css
  css/common.less
  css/main.css
  css/main.less
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
  proxy16/kit.js
  proxy16/node/torcontrol.js
  proxy16/proxy.js
  proxy16/transports.js
Labels: contribution type: 🧩 patch

#969 fix: call interface small issue
  js/bastyonCalls/bastyonCalls.min.js
Labels: contribution type: 🐛 fix

#972 fix: donations page localization change issues
  components/donations/index.js
Labels: contribution type: 🐛 fix

#973 patch: notifications and fa icons paths
  js/satolist.js
  proxy16/node/notifications.js
Labels: contribution type: 🧩 patch

#975 fix: proxy, logs
  proxy16/logger.js
  proxy16/node/notifications.js
Labels: contribution type: 🐛 fix

#974 fix: application network transport system
  components/system16/index.js
  components/transportsmanagement/templates/settings.html
  js/app.js
  package-lock.json
  package.json
  proxy16/kit.js
  proxy16/node/applications.js
  proxy16/node/torcontrol.js
  proxy16/package-lock.json
  proxy16/package.json
Labels: contribution type: 🐛 fix

#980 hotfix: proxy server shuts down on invalid response
  proxy16/package-lock.json
  proxy16/package.json
  proxy16/peertube/instance.js
  proxy16/transports.js
Labels: contribution type: 🔥 hotfix

#984 fix: build version badge for pre deploy
  .github/workflows/deploy.pulls.dev.yml
Labels: contribution type: 🐛 fix, contribution type: 🚦 maintanance

#987 fix: error in ipc and tor installed checks
  proxy16/ipc.js
  proxy16/node/torcontrol.js
Labels: contribution type: 🐛 fix

#986 patch: show answers for blocked comments
  components/comments/index.css
  components/comments/index.less
Labels: contribution type: 🧩 patch

#997 patch: better nickname placeholder
  components/test/index.css
  components/test/index.less
  localization/it.js
  localization/ru.js
Labels: contribution type: 🧩 patch

#994 patch: set minimal boost to 0.1
  components/comments/index.js
  components/donate/index.js
  components/donate/templates/index.html
  components/pkoin/index.js
  js/satolist.js
Labels: contribution type: 🧩 patch

#993 patch: better locale for audio post stats
  components/share/templates/url.html
  localization/en.js
  localization/ru.js
Labels: contribution type: 🧩 patch
