Repository pocketnetteam/pocketnet.gui, pull requests merged in 2023-01, with the labels that each got.

#852 repo: fix release workflow
  .github/workflows/build.release.yml
Labels: contribution type: 🚦 maintanance

#858 patch: boost page images
  components/boost/index.css
  components/boost/templates/index.html
  img/ads-on-bastyon1-ru.jpg
  img/ads-on-bastyon1_1.jpg
  img/basty-boost-img.jpg
  localization/en.js
  localization/ru.js
Labels: contribution type: 🧩 patch

#864 fix: share link with image
  js/kit.js
Labels: contribution type: 🐛 fix

#865 repo: workflow for conflicts analysis
  .github/workflows/analyze-conflicts.yml
Labels: contribution type: 🚦 maintanance

#880 patch: remove bad proxy16 node options
  proxy16/node/control.js
Labels: contribution type: 🧩 patch

#879 patch: remove christmas theme
  components/menu/index.css
  components/menu/index.js
  components/menu/index.less
  components/menu/templates/index.html
  img/chat_mobile.svg
  js/functions.js
Labels: contribution type: 🧩 patch

#877 patch: boost page update
  components/boost/index.css
  components/boost/index.less
  components/boost/templates/index.html
  localization/en.js
  localization/ru.js
Labels: contribution type: 🧩 patch

#875 patch: application icon menu and cordova camera
  components/applications/index.css
  components/applications/index.js
  components/applications/index.less
  components/camerapreview/index.css
  components/camerapreview/index.js
  components/camerapreview/index.less
  components/comments/index.js
  components/comments/templates/post.html
  components/menu/index.css
  components/menu/index.js
  components/menu/index.less
  components/menu/templates/index.html
  components/mobilesearch/index.js
  js/functions.js
  js/image-uploader.js
  js/satolist.js
  tpls/config.xml.tpl
  tpls/main.js.tpl
Labels: contribution type: 🧩 patch

#872 patch: mass mailing access conditions
  js/satolist.js
Labels: contribution type: 🧩 patch

#871 feat: user block confirmation banner
  components/commentBanner/index.css
  components/commentBanner/index.js
  components/commentBanner/index.less
  components/commentBanner/templates/index.html
  components/lenta/index.css
  components/lenta/index.js
  components/lenta/index.less
  components/lenta/templates/metmenu.html
  components/lenta/templates/share.html
  components/lenta/templates/sharevideo.html
  components/lenta/templates/sharevideolight.html
  components/post/index.js
  css/common.css
  css/common.less
  js/satolist.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/ru.js
Labels: contribution type: ✨ feature

#868 fix: mnemonic phrase popup on mobile
  components/pkview/index.css
  components/pkview/index.less
Labels: contribution type: 🐛 fix

#851 fix: small localization issue
  localization/ru.js
Labels: contribution type: 🐛 fix

#780 feat: p2p audio and video calls
  js/_map.js
  js/bastyonCalls/bastyonCalls.min.js
  js/satolist.js
  localization/ru.js
  sounds/busy.mp3
  sounds/calling.mp3
  sounds/connected.mp3
  sounds/hangup.mp3
  sounds/incoming.mp3
  tpls/index.html.tpl
  tpls/index.php.tpl
  tpls/index_el.html.tpl
  tpls/indexcordova.html.tpl
Labels: contribution type: ✨ feature

#796 feat: audio files upload support
  components/leftpanel/index.js
  components/leftpanel/templates/menu.html
  components/lenta/index.css
  components/lenta/index.js
  components/lenta/index.less
  components/main/index.js
  components/menu/index.js
  components/navigation/index.js
  components/share/index.css
  components/share/index.js
  components/share/index.less
  components/share/templates/postline.html
  components/share/templates/url.html
  components/uploadpeertube/index.js
  components/uploadpeertube/templates/index.html
  js/kit.js
  js/peertube.js
  localization/de.js
  localization/en.js
  localization/es.js
  localization/fr.js
  localization/it.js
  localization/kr.js
  localization/ru.js
  localization/zh.js
Labels: contribution type: ✨ feature

#723 feat: store images on peertube servers
  components/imagegallery/templates/image.html
  js/app.js
  js/functions.js
  js/image-uploader.js
  js/logger.js
  js/peertube.js
  js/satolist.js
  js/user.js
Labels: contribution type: ✨ feature

#856 feat: share post from other social networks
  components/share/index.js
  cordova/cordova-universal-links-plugin/hooks/lib/android/manifestWriter.js
  cordova/package-lock.json
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: contribution type: ✨ feature

#682 feat: profile activities page
  components/activities/index.css
  components/activities/index.js
  components/activities/index.less
  components/activities/templates/content.html
  components/activities/templates/filters.html
  components/activities/templates/index.html
  components/comments/index.js
  components/complain/index.css
  components/userpage/index.js
  components/userpage/index.less
  components/userslist/index.js
  components/userslist/templates/users.html
  css/main.css
  css/main.less
  js/_map.js
  js/main.js
  js/satolist.js
  localization/en.js
  localization/ru.js
  proxy16/node/rpc.js
Labels: contribution type: ✨ feature, deploy.dev

#892 fix: lenta component ui
  components/lenta/index.css
  components/lenta/index.js
  components/lenta/index.less
  components/lenta/templates/metmenu.html
  components/lenta/templates/sharevideolight.html
  js/satolist.js
  localization/en.js
Labels: contribution type: 🐛 fix

#889 patch: activities page images support
  components/activities/index.css
  components/activities/index.js
  components/activities/index.less
  components/activities/templates/content.html
Labels: contribution type: 🧩 patch

#885 patch: boost page texts
  js/satolist.js
  localization/en.js
  localization/ru.js
Labels: contribution type: 🧩 patch
