Repository pocketnetteam/pocketnet.gui, pull requests merged in 2024-02, with the labels that each got.

#1183 fix: unspents update, comment vote css, subscribers feed
  components/comments/index.css
  components/comments/index.less
  components/lenta/index.js
  js/app.js
  js/lib/client/actions.js
  package.json
Labels: contribution type: 🐛 fix

#1190 patch: root and proxy16 packages
  package-lock.json
  package.json
  proxy16/package-lock.json
  proxy16/package.json
Labels: deploy.dev, contribution type: 🧩 patch, contribution type: 🚦 maintanance

#1187 patch: tor snowflake bridges configurations
  proxy16/node/torcontrol.js
Labels: deploy.dev, contribution type: 🧩 patch

#1193 patch: update stun/turn list
  js/lib/client/p2pvideo.js
  proxy16/node/torcontrol.js
Labels: contribution type: 🧩 patch

#1196 patch: npm audit fixes and tor stun limits
  package-lock.json
  proxy16/node/torcontrol.js
Labels: contribution type: 🧩 patch

#1203 fix: localstorage size
  css/common.css
  css/common.less
  js/satolist.js
  package.json
Labels: contribution type: 🐛 fix

#1204 rpc-jury
  proxy16/node/rpc.js
  proxy16/server/cache.js
Labels: deploy.dev

#1179 feat: add secure connection support for proxy16
  package-lock.json
  package.json
  proxy16/cli.js
  proxy16/ipc.js
  proxy16/kit.js
  proxy16/node/node.js
  proxy16/node/rpc.js
  proxy16/node/wss.js
Labels: contribution type: ✨ feature

#1207 fix: missing sws prop in nodes file
  proxy16/node/manager.js
Labels: contribution type: 🐛 fix
