Repository pocketnetteam/pocketnet.gui, pull requests merged in 2024-03, with the labels that each got.

#1212 patch: vulnerable dependencies fixes
  package-lock.json
Labels: contribution type: 🧩 patch

#1210 patch: update static nodes list
  proxy16/kit.js
Labels: contribution type: 🧩 patch

#1209 feat: coingecko pkoin aggregated rate
  proxy16/exchanges.js
Labels: contribution type: ✨ feature

#1175 feat: remote peertube servers list
  .github/workflows/deploy.pulls.dev.yml
  .github/workflows/deploy.web.yml
  .github/workflows/night.bastyon.com.yml
  .github/workflows/night.test.bastyon.com.yml
  .github/workflows/pre.pocketnet.app.yml
  .github/workflows/test.pocketnet.app.yml
  .gitignore
  minimize.js
  package-lock.json
  package.json
  proxy16/config.json
  proxy16/dockerfile
  proxy16/gruntfile.js
  proxy16/package-lock.json
  proxy16/package.json
  proxy16/peertube/roy.js
  proxy16/proxy.js
Labels: contribution type: ✨ feature

#1213 fix: small changes
  components/lenta/index.js
  components/share/templates/url.html
  js/functions.js
  js/satolist.js
  package.json
  proxy16/node/notifications.js
  proxy16/proxy.js
Labels: contribution type: 🐛 fix
