Repository pocketnetteam/pocketnet.gui, pull requests merged in 2024-09, with the labels that each got.

#1280 fix: 0209 small fix
  components/authorn/index.js
  js/satolist.js
  package.json
Labels: contribution type: 🐛 fix

#1281 patch: notifications
  components/channel/index.js
  components/channel/templates/index.html
  components/earnings/index.css
  components/earnings/index.js
  components/earnings/index.less
  components/earnings/templates/index.html
  components/earnings/templates/monetizationwrapper.html
  components/lenta/index.js
  components/post/index.css
  components/post/index.js
  components/post/index.less
  js/app.js
  js/vendor/plyr.js
  localization/en.js
  localization/ru.js
  package.json
  peertube/284.chunk.js.map
  peertube/300.chunk.js.map
  peertube/524.chunk.js.map
  peertube/875.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
  proxy16/node/notifications.js
  proxy16/node/notificationsDictionary.js
Labels: contribution type: 🧩 patch

#1288 fix: notification style
  css/main.css
  css/main.less
  js/satolist.js
  package.json
Labels: contribution type: 🐛 fix

#1290 patch: easynode support
  components/nodecontrol/templates/nodecontentmanage.html
  localization/en.js
  localization/ru.js
Labels: contribution type: 🧩 patch

#1291 hotfix: calls
  js/bastyonCalls/bastyonCalls.min.js
  package.json
Labels: contribution type: 🔥 hotfix

#1292 patch: electron monetization, removed comments
  js/lib/client/sdk.js
  package.json
  tpls/index_el.html.tpl
Labels: contribution type: 🧩 patch

#1293 patch: android foregound service
  components/uploadpeertube/index.js
  cordova/cordova-plugin-run-in-background/plugin.xml
  cordova/cordova-plugin-run-in-background/src/android/ForegroundService.java
  cordova/cordova-plugin-run-in-background/www/background-mode.js
  js/app.js
  js/functionsfirst.js
  js/satolist.js
  localization/en.js
  localization/ru.js
  package.json
Labels: contribution type: 🧩 patch

#1295 patch: set check updates every 1 hour
  proxy16/kit.js
  tpls/main.js.tpl
Labels: contribution type: 🧩 patch

#1297 patch: stream small fix
  components/post/index.css
  components/post/index.less
  package.json
Labels: contribution type: 🧩 patch

#1299 patch: add barteron
  config/Bastyon.json
  js/functionsfirst.js
  js/satolist.js
  package.json
Labels: contribution type: 🧩 patch

#1300 fix: update barteron domen
  config/Bastyon.json
Labels: contribution type: 🐛 fix

#1304 patch: fill here the pr title
  .github/workflows/deploy.pulls.dev.yml
Labels: contribution type: 🧩 patch

#1302 fix: new page
  components/fastsend/index.css
  components/fastsend/index.js
  components/fastsend/index.less
  components/fastsend/templates/index.html
  components/fastsend/templates/info.html
  components/fastsend/templates/inputs.html
  js/_map.js
Labels: contribution type: 🐛 fix, deploy.dev
