Repository pocketnetteam/pocketnet.gui, pull requests merged in 2024-01, with the labels that each got.

#1172 patch: set package version to 0.8.77
  package-lock.json
  package.json
Labels: contribution type: 🧩 patch

#1173 repo: allow failed jobs on release
  .github/workflows/build.release.yml
Labels: contribution type: 🚦 maintanance

#1155 fix: cursor dragging leading to post close
  components/lenta/index.js
  components/post/index.js
  js/functions.js
Labels: contribution type: 🐛 fix

#1166 fix: user icons spacing issue in profile
  components/userslist/index.css
Labels: contribution type: 🐛 fix, deploy.dev

#1167 fix: negative reputation showed as zero
  js/lib/client/sdk.js
Labels: contribution type: 🐛 fix, deploy.dev

#1178 repo: fix night test web deploy
  .github/workflows/night.test.bastyon.com.yml
Labels: contribution type: 🐛 fix, contribution type: 🚦 maintanance

#1177 fix: remove electron reload package as not used
  .gitignore
  cordova/ul_web_hooks/android/android_web_hook.html
  package-lock.json
  package.json
  proxy16/package.json
Labels: contribution type: 🐛 fix
