Repository pocketnetteam/pocketnet.gui, pull requests merged in 2024-04, with the labels that each got.

#1217 patch: remote test peertube servers list
  proxy16/proxy.js
Labels: contribution type: 🧩 patch

#1216 fix: api promises
  components/boost/templates/index.html
  components/help/index.js
  components/howtobuy/templates/index.html
  components/test/index.js
  components/wallet/templates/buy.html
  img/tapbit.png
  js/faq.js
  js/lib/client/api.js
  js/lib/client/sdk.js
  js/satolist.js
  localization/en.js
  localization/ru.js
  package.json
  tpls/embedVideo.php.tpl
  tpls/index.html.tpl
  tpls/index.php.tpl
Labels: contribution type: 🐛 fix

#1221 patch: add missing proxy16 build stage
  .github/workflows/build.dev.yml
  .github/workflows/deploy.branch.dev.yml
  .github/workflows/deploy.pulls.dev.yml
  .github/workflows/night.bastyon.com.yml
  .github/workflows/night.test.bastyon.com.yml
Labels: contribution type: 🧩 patch

#1223 hotfix: remote peertube list support for electron builder flow
  package.json
  proxy16/dockerfile
Labels: contribution type: 🔥 hotfix

#1225 patch: set version to 0.8.85
  package-lock.json
  package.json
Labels: contribution type: 🧩 patch
