Repository pocketnetteam/pocketnet.gui, pull requests merged in 2025-02, with the labels that each got.

#1402 fix: group videos
  components/lenta/index.css
  components/lenta/index.js
  components/lenta/index.less
  components/lenta/templates/groupshares.html
  js/satolist.js
  package.json
  tpls/config.xml.tpl
Labels: contribution type: 🐛 fix

#1403 fix: filter i2p addess
  components/complain/index.js
  package.json
  proxy16/node/manager.js
  proxy16/node/node.js
Labels: contribution type: 🐛 fix

#1409 fix: add label
  components/leftpanel/index.css
  components/leftpanel/index.js
  components/leftpanel/index.less
  components/leftpanel/templates/footer.html
  localization/en.js
  package.json
Labels: contribution type: 🐛 fix

#1411 fix: top videos, p sub
  components/lenta/index.js
  components/lenta/templates/share.html
  components/main/index.js
  config/Bastyon.json
  css/common.css
  css/common.less
  js/kit.js
  js/lib/apps/index.js
  js/lib/apps/sdk.js
  js/satolist.js
  package.json
Labels: contribution type: 🐛 fix

#1415 fix: fill here the pr title
  .github/workflows/build.release.aur.yml
Labels: contribution type: 🐛 fix

#1416 fix: aur deploy action
  .github/workflows/build.release.aur.yml
Labels: contribution type: 🐛 fix

#1417 hotfix: fill here the pr title
  .github/workflows/build.release.aur.yml
Labels: contribution type: 🔥 hotfix

#1418 hotfix: aur deploy
  .github/workflows/build.release.aur.yml
Labels: contribution type: 🔥 hotfix

#1419 hotfix: delete aur ci
  .github/workflows/build.release.aur.yml
Labels: contribution type: 🔥 hotfix

#1420 patch: dev:bastyon:rmupdate
  js/satolist.js
  minimize.js
  package.json
  tpls/main.js.tpl
Labels: contribution type: 🧩 patch
