Repository pocketnetteam/pocketnet.gui, pull requests merged in 2025-01, with the labels that each got.

#1354 fix: pr
  proxy16/pocketnet.js
  proxy16/proxy.js
  proxy16/wallet/wallet.js
Labels: contribution type: 🐛 fix

#1355 fix: pr2
  proxy16/proxy.js
Labels: contribution type: 🐛 fix

#1356 fix: proxy optimizations
  proxy16/pocketnet.js
  proxy16/proxy.js
  proxy16/server/cache.js
Labels: contribution type: 🐛 fix

#1357 fix: proxy optimizations
  js/satolist.js
  proxy16/server/cache.js
Labels: contribution type: 🐛 fix

#1361 patch: block explorer
  components/application/index.css
  components/application/index.js
  components/application/index.less
  components/home/index.js
  components/leftpanel/index.js
  components/leftpanel/templates/footer.html
  components/transactionslist/index.js
  components/transactionslist/templates/list.html
  components/transactionview/index.css
  components/transactionview/index.js
  components/transactionview/index.less
  components/transactionview/templates/tx.html
  components/userpage/index.js
  components/userpage/templates/bgcaption.html
  components/userpage/templates/contents.html
  config/Bastyon.json
  css/main.css
  css/main.less
  js/lib/apps/index.js
  package.json
  proxy16/server/cache.js
Labels: contribution type: 🧩 patch

#1364 patch: p sub
  chat/matrix-element.1.js
  chat/matrix-element.1.js.map
  chat/matrix-element.1.min.js
  chat/matrix-element.1.min.js.map
  chat/matrix-element.19.js
  chat/matrix-element.19.js.map
  chat/matrix-element.19.min.js
  chat/matrix-element.19.min.js.map
  chat/matrix-element.2.js
  chat/matrix-element.2.js.map
  chat/matrix-element.2.min.js
  chat/matrix-element.2.min.js.map
  components/actions/templates/state.html
  components/articlev/index.js
  components/authorn/index.css
  components/authorn/index.js
  components/authorn/index.less
  components/authorn/templates/fbuttonsrow.html
  components/getpaidsubscription/index.css
  components/getpaidsubscription/index.js
  components/getpaidsubscription/index.less
  components/getpaidsubscription/templates/error.html
  components/getpaidsubscription/templates/form.html
  components/getpaidsubscription/templates/index.html
  components/lenta/index.js
  components/lenta/templates/share.html
  components/lenta/templates/sharearticle.html
  components/lenta/templates/sharevideo.html
  components/lenta/templates/sharevideolight.html
  components/managepaidsubscription/index.css
  components/managepaidsubscription/index.js
  components/managepaidsubscription/index.less
  components/managepaidsubscription/templates/error.html
  components/managepaidsubscription/templates/form.html
  components/managepaidsubscription/templates/index.html
  components/post/index.js
  components/share/index.js
  components/share/templates/settings.html
  css/main.css
  css/main.less
  img/on-fire.png
  img/torch.png
  js/_map.js
  js/effects.js
  js/kit.js
  js/lib/apps/sdk.js
  js/lib/client/sdk.js
  js/satolist.js
  localization/en.js
  localization/ru.js
  package.json
  proxy16/node/rpc.js
  proxy16/server/cache.js
Labels: contribution type: 🧩 patch

#1365 fix: cover images
  components/application/templates/frameremote.html
  components/authorn/index.css
  components/authorn/index.js
  components/authorn/index.less
  components/authorn/templates/bg.html
  components/comments/index.js
  components/embeding/index.js
  components/embeding/templates/index.html
  components/getpaidsubscription/index.css
  components/getpaidsubscription/index.js
  components/getpaidsubscription/index.less
  components/lenta/index.js
  components/lenta/templates/sharearticle.html
  components/managepaidsubscription/index.css
  components/managepaidsubscription/index.js
  components/managepaidsubscription/index.less
  components/menu/index.css
  components/menu/index.less
  components/menu/templates/index.html
  components/post/index.css
  components/post/index.js
  components/post/index.less
  css/main.css
  css/main.less
  js/app.js
  js/functions.js
  js/functionsfirst.js
  js/kit.js
  js/lib/apps/index.js
  js/lib/apps/sdk.js
  js/lib/client/sdk.js
  js/satolist.js
  localization/en.js
  localization/ru.js
  package.json
  tpls/main.js.tpl
Labels: contribution type: 🐛 fix

#1366 fix: channel view
  chat/matrix-element.7.js
  chat/matrix-element.7.js.map
  chat/matrix-element.7.min.js
  chat/matrix-element.7.min.js.map
  components/authorn/index.css
  components/authorn/index.js
  components/authorn/index.less
  components/authorn/templates/uinfo.html
  components/channel/index.css
  components/channel/index.js
  components/channel/index.less
  components/channel/templates/index.html
  package.json
  proxy16/peertube/index.js
  proxy16/peertube/instance.js
  proxy16/peertube/roy.js
  proxy16/proxy.js
Labels: contribution type: 🐛 fix

#1367 fix: cover uploading
  components/authorn/index.js
  components/camerapreview/index.js
  components/menu/index.css
  components/menu/index.less
  css/main.css
  css/main.less
  localization/en.js
  localization/ru.js
  package.json
Labels: contribution type: 🐛 fix

#1368 fix: articles fix
  css/main.css
  css/main.less
  js/functions.js
  js/functionsfirst.js
  js/lib/apps/index.js
  js/lib/apps/sdk.js
  js/lib/client/actions.js
  js/satolist.js
  package.json
Labels: contribution type: 🐛 fix

#1370 fix: urls in comments
  components/authorn/templates/uinfo.html
  components/comments/index.js
  components/comments/templates/list.html
  js/lib/client/actions.js
  js/lib/client/sdk.js
  js/satolist.js
  localization/en.js
  localization/ru.js
  package.json
Labels: contribution type: 🐛 fix

#1371 fix: tx storage update
  components/authorn/templates/fbuttonsrow.html
  js/app.js
  js/lib/client/actions.js
  js/satolist.js
Labels: contribution type: 🐛 fix

#1372 fix: animation
  components/authorn/index.css
  components/authorn/index.js
  components/authorn/index.less
  components/channel/index.css
  components/channel/index.js
  components/channel/index.less
  css/main.css
  css/main.less
  js/functions.js
  package.json
Labels: contribution type: 🐛 fix

#1373 fix: menu shadow pointer events
  components/menu/index.css
  components/menu/index.less
  package.json
Labels: contribution type: 🐛 fix

#1376 fix: video cache force update
  js/peertube.js
Labels: contribution type: 🐛 fix

#1379 fix: small fix
  components/authorn/index.js
  components/embeding/index.js
  components/external/templates/pay.html
  components/getpaidsubscription/templates/form.html
  components/lenta/index.js
  config/Bastyon.json
  js/functionsfirst.js
  js/lib/external/index.min.js
  js/satolist.js
  localization/en.js
  localization/ru.js
  package.json
  proxy16/kit.js
  tpls/index.php.tpl
Labels: contribution type: 🐛 fix

#1380 fix: fix
  components/authorn/index.js
  components/comments/templates/list.html
  js/lib/apps/sdk.js
  js/satolist.js
  package.json
  php/og.php
Labels: contribution type: 🐛 fix

#1381 feat: example of nginx configuration
  nginx.conf
Labels: contribution type: ✨ feature

#1383 fix: player, php og
  components/application/index.css
  components/application/index.less
  components/authorn/index.css
  components/authorn/index.less
  components/lenta/index.css
  components/lenta/index.js
  components/lenta/index.less
  components/lenta/templates/groupshares.html
  components/lenta/templates/shares.html
  components/main/index.js
  components/share/index.js
  js/satolist.js
  js/vendor/plyr.js
  localization/ru.js
  package.json
  peertube/284.chunk.js.map
  peertube/300.chunk.js.map
  peertube/524.chunk.js.map
  peertube/875.chunk.js.map
  peertube/embed.html
  peertube/video-embed.bundle.js
  peertube/video-embed.bundle.js.map
  peertube/video-embed.css.map
  php/og.php
Labels: contribution type: 🐛 fix

#1384 fix: node direct request
  proxy16/node/rpc.js
  proxy16/proxy.js
Labels: contribution type: 🐛 fix

#1386 fix: wait if reject
  js/lib/client/actions.js
Labels: contribution type: 🐛 fix

#1387 fix: wait reject 2
  js/lib/client/actions.js
Labels: contribution type: 🐛 fix

#1388 fix: reject/wait
  js/lib/client/actions.js
  package.json
Labels: contribution type: 🐛 fix

#1391 patch: open stream mobile
  components/authorn/index.js
  components/lenta/index.js
  package.json
Labels: contribution type: 🧩 patch

#1392 fix: small fix
  components/post/index.js
  js/satolist.js
  package.json
Labels: contribution type: 🐛 fix

#1394 fix: combine pulls action
  .github/workflows/deploy.pulls.dev.yml
Labels: contribution type: 🐛 fix

#1398 fix: deleted comment
  components/activities/index.js
  components/comments/index.js
  components/complain/index.js
  js/lib/client/sdk.js
  localization/ru.js
  package.json
  php/api.php
  php/og.php
Labels: contribution type: 🐛 fix

#1400 feat: workflow for releasing AUR application
  .github/workflows/build.release.aur.yml
Labels: contribution type: ✨ feature

#1401 fix: cordova activity
  components/csaepolicy/index.css
  components/csaepolicy/index.js
  components/csaepolicy/index.less
  components/csaepolicy/templates/en.html
  components/csaepolicy/templates/index.html
  js/_map.js
  js/satolist.js
  package.json
  tpls/config.xml.tpl
Labels: contribution type: 🐛 fix
